Faut tout review goodluck
ReDevCafe/Tsubaki pull request #1
Opened 2024-11-25 18:44 UTC by AmeliaCute

2024-11-25 18:55 UTC, EltyDev commented on source/configuration/Commands.cs
La POO existe

2024-11-25 19:01 UTC, EltyDev commented on source/Program.cs
> +            GatewayIntents = GatewayIntents.All, // un peu la flemme mais apres on pourra def les vrai autorisations
Oui

2024-11-25 19:07 UTC, EltyDev commented on source/Program.cs
> +        Console.WriteLine(log);
Faire un vrai système de log

2024-11-25 19:12 UTC, KazeRequiem commented
La poo ça existe oui, faut des classes abstraites et tout là ça va pas

2024-11-25 19:14 UTC, EltyDev requested changes
Sur les handlers, je pense qu'on peut faire une classe abstrait pour moduler tout ça

2024-11-25 19:15 UTC, KazeRequiem commented on source/configuration/Commands.cs
c'est bien vrai

2024-11-25 19:19 UTC, EltyDev commented on source/configuration/ConfigFile.cs
> +    public class Config
Privé les champs d'une classe

2024-11-26 13:00 UTC, AmeliaCute commented on source/configuration/ConfigFile.cs
> +    public class Config
Comment ca?

2024-11-26 17:35 UTC, EltyDev commented on source/configuration/ConfigFile.cs
> +    public class Config
pas public

2024-11-26 19:13 UTC, AmeliaCute commented on source/configuration/ConfigFile.cs
> +    public class Config
ah lmao

2024-11-26 22:24 UTC, KazeRequiem commented on source/configuration/ConfigFile.cs
> +    public class Config
private et tu fous des get/set

2024-11-27 14:21 UTC, EltyDev commented on source/command/CommandManager.cs
> +                SayCommand => new SlashCommandBuilder()
Pourquoi passer un builder à coté autant le faire dans la classe abstrait non ?

2024-11-27 14:22 UTC, EltyDev commented on source/configuration/ConfigFile.cs
> +        public string Token { get; set; }
Mets les champs de tes classes en privé (hors exceptions)

2024-11-27 14:23 UTC, EltyDev commented on source/maintenance/Logger.cs
ça à l'air cool

2024-11-27 14:24 UTC, EltyDev requested changes
Quelque truc à faire sinon comment je t'ai dis voir si les handlers sont pas faisable de manière modulable

2025-01-28 14:35 UTC, EltyDev commented on source/configuration/ConfigFile.cs
> +        public string Token { get; set; }
!!!!!

2025-01-28 14:36 UTC, EltyDev requested changes
Bruh

2025-01-28 18:33 UTC, AmeliaCute commented on source/configuration/ConfigFile.cs
> +        public string Token { get; set; }
pas serializable si mis en privee de memoire

2025-01-29 10:28 UTC, EltyDev commented on source/configuration/ConfigFile.cs
> +        public string Token { get; set; }
ok

2025-01-29 10:29 UTC, merged